//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoTrade.DAL.Provider
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlgoTradeContainer : DbContext
    {
        public AlgoTradeContainer()
            : base("name=AlgoTradeContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AlgoRule> AlgoRules { get; set; }
        public DbSet<EnumType> EnumTypes { get; set; }
        public DbSet<Log> Logs { get; set; }
        public DbSet<Position> Positions { get; set; }
        public DbSet<RiskRule> RiskRules { get; set; }
        public DbSet<SymbolList> SymbolLists { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Transaction> Transactions { get; set; }
    }
}
