//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoTrade.DAL.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlgoRule
    {
        public int ID { get; set; }
        public string Symbol { get; set; }
        public string BuyFeatureTexture { get; set; }
        public Nullable<int> PositionTypeValue { get; set; }
        public string PositionTypeName { get; set; }
        public Nullable<int> ActionTypeValue { get; set; }
        public string ActionTypeName { get; set; }
        public Nullable<double> Accuracy { get; set; }
        public bool IsEnable { get; set; }
        public System.Guid Token { get; set; }
        public string SellFeatureTexture { get; set; }
        public string Description { get; set; }
        public Nullable<double> Profit { get; set; }
    }
}
