//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoTrade.DAL.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnumType
    {
        public EnumType()
        {
            this.Logs = new HashSet<Log>();
            this.Positions = new HashSet<Position>();
            this.Transactions = new HashSet<Transaction>();
            this.Transactions1 = new HashSet<Transaction>();
            this.Transactions2 = new HashSet<Transaction>();
        }
    
        public int ID { get; set; }
        public string EnumName { get; set; }
        public string EnumType1 { get; set; }
        public Nullable<int> EnumValue { get; set; }
    
        public virtual ICollection<Log> Logs { get; set; }
        public virtual ICollection<Position> Positions { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<Transaction> Transactions1 { get; set; }
        public virtual ICollection<Transaction> Transactions2 { get; set; }
    }
}
