//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoTrade.DAL.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public long ID { get; set; }
        public string LogType { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> LogTypeID { get; set; }
    
        public virtual EnumType EnumType { get; set; }
    }
}
