//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoTrade.DAL.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public int PositionID { get; set; }
        public string Symbol { get; set; }
        public Nullable<decimal> CostBase { get; set; }
        public Nullable<decimal> CurrentPrice { get; set; }
        public Nullable<int> Shares { get; set; }
        public Nullable<int> PositionTypeID { get; set; }
        public string PositionTypeName { get; set; }
    
        public virtual EnumType EnumType { get; set; }
    }
}
