//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoTrade.DAL.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskRule
    {
        public int ID { get; set; }
        public string RiskRulesTypeValue { get; set; }
        public string RiskRulesTypeName { get; set; }
        public double RuleValue { get; set; }
        public string AlgoRuleName { get; set; }
        public string Symbol { get; set; }
        public Nullable<System.Guid> AlgoRuleID { get; set; }
    }
}
