//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoTrade.DAL.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class SymbolList
    {
        public int ID { get; set; }
        public string Symbol { get; set; }
        public string Instrument { get; set; }
        public string Market { get; set; }
        public string MarketType { get; set; }
        public Nullable<double> CurrentPrice { get; set; }
    }
}
