//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoTrade.DAL.Provider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransID { get; set; }
        public string Symbol { get; set; }
        public Nullable<int> ActionTypeID { get; set; }
        public string ActionTypeName { get; set; }
        public Nullable<int> ConditionTypeID { get; set; }
        public string ConditionTypeName { get; set; }
        public Nullable<int> PositionTypeID { get; set; }
        public string PositionTypeName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> IsPaperTrade { get; set; }
        public Nullable<System.DateTime> TradingDate { get; set; }
        public Nullable<System.Guid> AlgoRuleToken { get; set; }
        public Nullable<int> Shares { get; set; }
    
        public virtual EnumType EnumType { get; set; }
        public virtual EnumType EnumType1 { get; set; }
        public virtual EnumType EnumType2 { get; set; }
    }
}
